# The development stack of this application
---

services:

  server:
    image: sth123/pdf-automator-server
    container_name: pdf-automator-server
    hostname: pdf-automator-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80/health-check | grep -i 'OK'"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 20s
    ports:
      - ${PORT}:80
    networks:
      - default
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      REDIS_HOST: pdf-automator-database
    volumes:
      - ${APPDATA}/documents:/app/private/documents
    depends_on:
      - database
    working_dir: /app
    tty: true

  database:
    image: sth123/pdf-automator-database 
    container_name: pdf-automator-database
    hostname: pdf-automator-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - default
    env_file:
      - ./.env
    volumes:
      - ${APPDATA}/database/d–∞ta:/data
      - ./redis.config:/redis-stack.conf
    tty: true

networks:
  default:
    name: pdf-automator